### ISSUE TITLE
Push dev2 to master

### ISSUE THREAD

**Issue by jonnenauha** [realXtend/WebTundra#82]
@antont @cadaver @cvetan5 

We should tag the current master as version `X.Y` (i would prefer not using the `v` prefix. Then push dev2 as the new master. This might require a force push. Though I'm quite sure I started with master, then just did git moves (eg. src > src1) and removes to clean things out.

There seems to already be a tag `v1.1`. We can keep this naming scheme or retag with `1.0` and proceed with those kind of tags.

IMO tags are enough and we don't need a `stable` branch. Ofc people can and should use feature branches, but just doing tags from master is probably enough for our current work flow.

**Comment by antont** [comment]
no force push is required IIRC, should go with normal push like you also recall.

i think dev2 should become tag 2.0 once released, that communicates the changing API well is the prev release was 1.0.

i suggest we keep using standard git flow where master is previous release and there's a dev branch & feature branches. so pushing to master is the last thing in the release process. so i propose as a part of the 2.0 release we push dev2 to dev and when continue work towards 2.1 etc there.

**Comment by jonnenauha** [comment]
I don't like the idea of `master` being the last stable release. I've never seen this anywhere except three.js repo. It's just annoing when you go and want to look at the latest code that you have to swap branches in the github UI, I don't like it one bit.

Github has a very nice tag + release feature and people can download releases like that. If they want to use git we can document and update `stable` branch on releases as well or update the main doc with latest release tag name and how to clone it properly.

IMO master is the latest development HEAD of the repo.

**Comment by antont** [comment]
In addition to `three.js` also `tundra` does this, i.e. applies `git flow`. These are the two projects that are close to `WebTundra` so would be confusing to make an exception here. Was a surprise to me that you'd suggest otherwise.

That said, you seem to be right that not everyone is using it -- didn't find any summary so checked some biggies in the JS land and these develop in `master`:

- https://github.com/jquery/jquery 
- https://github.com/facebook/react
- https://github.com/Polymer/polymer
- https://github.com/jashkenas/underscore
- https://github.com/Microsoft/TypeScript
- https://github.com/jashkenas/coffeescript
- https://github.com/nodejs/node

These don't but have a `dev` branch instead: 

- https://github.com/twbs/bootstrap
- https://github.com/lhorie/mithril.js (calls it `next`)
- https://github.com/KhronosGroup/glTF

This was surprising too, I hadn't really thought of it when getting other projects so thought it was everywhere. Perhaps it is more standard in proprietary / customer projects than in open source -- for example this recent critique of it says:

> GitFlow is probably the most popular Git branching model in use today. It seems to be
> everywhere. It certainly is everywhere for me personally - practically every project at my current
> job uses it, and often it's the clients themselves who have chosen it.

from: http://endoflineblog.com/gitflow-considered-harmful (2015/05/03)

That argues for a single permanent branch.

I've found `git-flow` nice and practical. Seems clear that `master` is always the release. For example FIWARE manuals and other official documents can just refer to that and it's always the release. Don't have to go update links in the catalogue for example after each release when the currently released code is always in the same branch.

Also I've found it nice that can always compare the current development version with the previous release just by comparing `dev` or whatever am working on with `master`. Don't need to remember the tag of the prev release but can always diff against master when suspect that a bug has been introduced in new code after the previous release.

Finally it has seemed good to have `master` so that only actually released code goes in there. Work in `dev` can be more uncertain for example when a new approach is experimented with -- if we notice that some idea doesn't actually work it can be reverted (and even cleaned from history / that dev branch dropped) so that it never makes it to `master`. Have never done this in practice though but has seemed like a good option to have.

Anyways there's some data for info, will read that quite recent critique blog post & comments and think a bit more. From the comments there, GitLab folks made a similar argument and propose basically the same model as that blogger, in https://about.gitlab.com/2014/09/29/gitlab-flow/

**Comment by jonnenauha** [comment]
Well, Tundra kind of tried but ended up calling the dev branch `tundra2` which IMO there also should have been named `master` as well :) We ended up calling ours `admino_tundra` for some reason.

It's nice that you did some research on this. My feeling has been for a long time that `master` + pull requests + tags is the prevalent way in github/bitbucket git repos.

* `master`
 * for direct development
 * some repos seem to also require "core devs" to send PRs, even for smaller changes. I think this is too noisy and prefer "core devs" of the project to commit directly into master.
* `pull requests`
 * aka feature branches
 * external contributions and bigger internal features/refactoring
* `tags`
 * releases: github gives such a nice place and easy way of doing releases out of tags.
 * tags are extremely easy to 1) clone directly 2) jump to if you already have a clone 3) download zip/tar with single button from the web UI

I think we should `KISS` and go with this :) I think the git flow model might be nicer for big projects with a lot of contributors (though, as you said some of the biggest repos in github use the simpler dev-in-master model).

Doing lots of feature branches is overhead for one of us to manage the merges and stuff. We know this is at worst considerable amount of work from earlier rex projects. I do like to read and review code, esp. on this repo as the core is kind of my baby :) but I can trust every day commits to just land into master.

**Comment by cadaver** [comment]
Tundra-urho3d also commits development activity directly to master. I'm OK with Jonne's suggestion.

**Comment by cvetan5** [comment]
dev2 pushed to master
